import type { Layout } from "react-grid-layout";
import type { TerminalMode } from "@/types/adaptive-workspace";

/** Hyperliquid execution desk — optional focus mode (see docs/WEDGE_STRATEGY.md). */
export const WEDGE_PRODUCT_LABEL = "EXECUTION DESK";
export const FULL_WORKSPACE_LABEL = "EQUILIBRIUM TERMINAL";

export const WEDGE_DEFAULT_MODE: TerminalMode = "execution";
export const FULL_WORKSPACE_DEFAULT_MODE: TerminalMode = "balanced";

/** Panels that define the V1 wedge; never auto-hidden. */
export const WEDGE_CORE_PANEL_IDS = new Set<string>([
  "hyperbook",
  "chart",
  "intelligence",
  "ticket",
  "positions",
  "domladder",
  "slippageradar",
  "alerts",
  "surveillance",
  "operatormode",
  "dailybriefing",
  "marketstate",
  "dailyops",
  "operatorjournal",
  "newswire",
  "paperblotter",
  "liveblotter",
  "settlementledger",
]);

/** Museum / expansion panels — hidden until EXPAND or desk selection. */
export const WEDGE_ADVANCED_PANEL_IDS = new Set<string>([
  "macro",
  "copilot",
  "proactive",
  "teamdesk",
  "diagnostics",
  "alphalab",
  "infra",
  "decision",
  "knowledgegraph",
  "traderjournal",
  "research",
  "marketcoverage",
  "reliability",
  "ingestion",
  "intelengine",
  "collab",
  "enterpriseops",
  "integrations",
  "propintel",
  "ecosystem",
  "globalstrategy",
  "commercial",
  "execintel",
  "portfoliodesk",
  "derivdesk",
  "systemicintel",
  "memorydesk",
  "researchdesk",
  "platformdesk",
  "mobiledesk",
  "opscommand",
  "billingdesk",
  "deskops",
  "globaldesk",
  "operatordesk",
  "unifiedops",
  "liveexec",
  "marketcmd",
  "maturitydesk",
  "livedeploy",
  "explaindesk",
  "livementor",
]);

/** Default grid — Bloomberg-style: book/chart/ladder dominate, execution row, context below. */
export const WEDGE_V1_LAYOUT: Layout[] = [
  { i: "operatormode", x: 0, y: 0, w: 12, h: 2, minW: 6, minH: 2 },
  { i: "hyperbook", x: 0, y: 2, w: 3, h: 14, minW: 3, minH: 8 },
  { i: "chart", x: 3, y: 2, w: 6, h: 14, minW: 4, minH: 8 },
  { i: "domladder", x: 9, y: 2, w: 3, h: 7, minW: 2, minH: 4 },
  { i: "newswire", x: 9, y: 9, w: 3, h: 7, minW: 3, minH: 5 },
  { i: "ticket", x: 0, y: 16, w: 3, h: 6, minW: 2, minH: 5 },
  { i: "paperblotter", x: 0, y: 22, w: 3, h: 6, minW: 2, minH: 5 },
  { i: "liveblotter", x: 3, y: 22, w: 3, h: 6, minW: 2, minH: 5 },
  { i: "positions", x: 3, y: 16, w: 5, h: 12, minW: 3, minH: 6 },
  { i: "operatorjournal", x: 8, y: 16, w: 4, h: 12, minW: 3, minH: 6 },
  { i: "dailybriefing", x: 0, y: 28, w: 3, h: 5, minW: 3, minH: 4 },
  { i: "marketstate", x: 3, y: 28, w: 3, h: 5, minW: 3, minH: 4 },
  { i: "intelligence", x: 6, y: 28, w: 3, h: 5, minW: 2, minH: 4 },
  { i: "dailyops", x: 9, y: 28, w: 3, h: 5, minW: 3, minH: 4 },
  { i: "slippageradar", x: 0, y: 33, w: 4, h: 6, minW: 3, minH: 4 },
  { i: "alerts", x: 4, y: 33, w: 4, h: 6, minW: 2, minH: 4 },
  { i: "surveillance", x: 8, y: 33, w: 4, h: 6, minW: 3, minH: 4 },
];

/** Optional layout rows appended when Advanced panels are enabled. */
export const WEDGE_ADVANCED_LAYOUT_APPEND: Layout[] = [
  { i: "macro", x: 0, y: 21, w: 12, h: 3, minW: 6, minH: 2 },
  { i: "copilot", x: 0, y: 24, w: 4, h: 8, minW: 2, minH: 5 },
  { i: "traderjournal", x: 4, y: 24, w: 4, h: 8, minW: 3, minH: 5 },
  { i: "reliability", x: 8, y: 24, w: 4, h: 8, minW: 3, minH: 5 },
  { i: "dailyops", x: 0, y: 32, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "marketstate", x: 0, y: 41, w: 12, h: 8, minW: 6, minH: 6 },
  { i: "dailybriefing", x: 0, y: 49, w: 12, h: 8, minW: 6, minH: 6 },
  { i: "ecosystem", x: 0, y: 57, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "globalstrategy", x: 0, y: 66, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "commercial", x: 0, y: 75, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "execintel", x: 0, y: 84, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "portfoliodesk", x: 0, y: 93, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "derivdesk", x: 0, y: 102, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "systemicintel", x: 0, y: 111, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "memorydesk", x: 0, y: 120, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "researchdesk", x: 0, y: 129, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "platformdesk", x: 0, y: 138, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "mobiledesk", x: 0, y: 147, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "opscommand", x: 0, y: 156, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "billingdesk", x: 0, y: 165, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "deskops", x: 0, y: 174, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "globaldesk", x: 0, y: 183, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "operatordesk", x: 0, y: 192, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "unifiedops", x: 0, y: 201, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "liveexec", x: 0, y: 210, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "marketcmd", x: 0, y: 219, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "maturitydesk", x: 0, y: 228, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "livedeploy", x: 0, y: 237, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "explaindesk", x: 0, y: 246, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "operatorjournal", x: 0, y: 255, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "livementor", x: 0, y: 264, w: 12, h: 9, minW: 6, minH: 6 },
  { i: "operatormode", x: 0, y: 273, w: 12, h: 8, minW: 6, minH: 6 },
];

export const WEDGE_V1_COMMANDS = new Set([
  "/nav",
  "/trade",
  "/exec",
  "/chart",
  "/depth",
  "/liq",
  "/vol",
  "/intel",
  "/summarize",
  "/watch",
  "/unwatch",
  "/monitor",
  "/alerts",
  "/desk",
  "/expand",
  "/help",
  "/focus",
  "/guide",
  "/explain",
  "/operator",
  "/paper",
  "/blotter",
]);

export const WEDGE_ADVANCED_COMMANDS = new Set([
  "/macro",
  "/graph",
  "/journal",
  "/research",
  "/workspace",
  "/briefing",
  "/coverage",
  "/reliability",
  "/newswire",
  "/incidents",
  "/ingest",
  "/intelengine",
  "/collab",
  "/team",
  "/enterprise",
  "/integrations",
  "/propintel",
  "/ecosystem",
  "/globalstrategy",
  "/routine",
]);

export function isAdvancedWidget(widgetId: string): boolean {
  return WEDGE_ADVANCED_PANEL_IDS.has(widgetId);
}

export function mergeWedgeLayouts(
  core: Layout[],
  showAdvanced: boolean,
): Layout[] {
  if (!showAdvanced) return core;
  const ids = new Set(core.map((l) => l.i));
  const extra = WEDGE_ADVANCED_LAYOUT_APPEND.filter((l) => !ids.has(l.i));
  return [...core, ...extra];
}

/** Full multi-phase workspace (pre–wedge default). */
export const FULL_WORKSPACE_LAYOUT: Layout[] = [
  { i: "hyperbook", x: 0, y: 3, w: 4, h: 14, minW: 3, minH: 8 },
  { i: "chart", x: 4, y: 3, w: 5, h: 14, minW: 3, minH: 8 },
  { i: "macro", x: 0, y: 0, w: 12, h: 3, minW: 6, minH: 2 },
  { i: "intelligence", x: 9, y: 3, w: 3, h: 8, minW: 2, minH: 6 },
  { i: "copilot", x: 9, y: 11, w: 3, h: 3, minW: 2, minH: 4 },
  { i: "proactive", x: 9, y: 14, w: 3, h: 3, minW: 2, minH: 4 },
  { i: "ticket", x: 0, y: 14, w: 3, h: 10, minW: 2, minH: 8 },
  { i: "positions", x: 3, y: 14, w: 6, h: 10, minW: 4, minH: 6 },
  { i: "teamdesk", x: 0, y: 24, w: 6, h: 8, minW: 3, minH: 5 },
  { i: "alerts", x: 6, y: 24, w: 6, h: 8, minW: 2, minH: 5 },
  { i: "diagnostics", x: 0, y: 32, w: 6, h: 7, minW: 4, minH: 5 },
  { i: "alphalab", x: 6, y: 32, w: 6, h: 7, minW: 4, minH: 5 },
  { i: "infra", x: 0, y: 39, w: 12, h: 6, minW: 6, minH: 4 },
  { i: "domladder", x: 0, y: 45, w: 6, h: 8, minW: 4, minH: 6 },
  { i: "slippageradar", x: 6, y: 45, w: 6, h: 8, minW: 4, minH: 6 },
  { i: "decision", x: 0, y: 53, w: 6, h: 10, minW: 4, minH: 8 },
  { i: "surveillance", x: 6, y: 53, w: 6, h: 10, minW: 4, minH: 8 },
  { i: "knowledgegraph", x: 0, y: 63, w: 12, h: 12, minW: 8, minH: 10 },
  { i: "traderjournal", x: 0, y: 75, w: 6, h: 10, minW: 4, minH: 8 },
  { i: "research", x: 6, y: 75, w: 6, h: 10, minW: 4, minH: 8 },
  { i: "dailyops", x: 0, y: 85, w: 12, h: 11, minW: 8, minH: 9 },
  { i: "marketstate", x: 0, y: 96, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "dailybriefing", x: 0, y: 106, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "marketcoverage", x: 0, y: 116, w: 12, h: 12, minW: 8, minH: 10 },
  { i: "reliability", x: 0, y: 128, w: 12, h: 11, minW: 8, minH: 9 },
  { i: "newswire", x: 0, y: 139, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "ingestion", x: 0, y: 149, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "intelengine", x: 0, y: 159, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "collab", x: 0, y: 169, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "enterpriseops", x: 0, y: 179, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "integrations", x: 0, y: 189, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "propintel", x: 0, y: 199, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "ecosystem", x: 0, y: 209, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "globalstrategy", x: 0, y: 219, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "commercial", x: 0, y: 229, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "execintel", x: 0, y: 239, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "portfoliodesk", x: 0, y: 249, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "derivdesk", x: 0, y: 259, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "systemicintel", x: 0, y: 269, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "memorydesk", x: 0, y: 279, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "researchdesk", x: 0, y: 289, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "platformdesk", x: 0, y: 299, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "mobiledesk", x: 0, y: 309, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "opscommand", x: 0, y: 319, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "billingdesk", x: 0, y: 329, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "deskops", x: 0, y: 339, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "globaldesk", x: 0, y: 349, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "operatordesk", x: 0, y: 359, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "unifiedops", x: 0, y: 369, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "liveexec", x: 0, y: 379, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "marketcmd", x: 0, y: 389, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "maturitydesk", x: 0, y: 399, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "livedeploy", x: 0, y: 409, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "explaindesk", x: 0, y: 419, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "operatorjournal", x: 0, y: 429, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "livementor", x: 0, y: 439, w: 12, h: 10, minW: 8, minH: 8 },
  { i: "operatormode", x: 0, y: 449, w: 12, h: 9, minW: 8, minH: 7 },
];

export function resolveWorkspaceLayout(deskFocusMode: boolean): Layout[] {
  return deskFocusMode ? WEDGE_V1_LAYOUT : FULL_WORKSPACE_LAYOUT;
}
