import type { ComponentGuideEntry } from "@/types/operator-guide";

function entry(
  id: string,
  title: string,
  telemetry: string,
  operational: string,
  why: string,
  professional: string,
  interpretation: string,
  related: string[],
  workflows: string[],
  shortcuts: string[],
  useCases: string[],
  metrics: string[],
): ComponentGuideEntry {
  return {
    id,
    title,
    telemetry,
    operationalExplanation: operational,
    whyItMatters: why,
    professionalUsage: professional,
    marketInterpretation: interpretation,
    relatedSystems: related,
    workflowConnections: workflows,
    shortcuts,
    useCases,
    relatedMetrics: metrics,
  };
}

const CORE: ComponentGuideEntry[] = [
  entry(
    "hyperbook",
    "HyperBook",
    "L2 DEPTH",
    "Real-time level-2 order book for the active perpetual. Aggregates bid/ask levels with cumulative size and spread.",
    "Liquidity is the constraint on every institutional fill. Without depth context, execution quality cannot be judged.",
    "Professionals scan top-of-book spread first, then depth walls within 10–25 bps of mid for absorption or vacuum risk.",
    "Thick bid stack + tightening spread often signals passive support; ask-heavy book with widening spread warns of supply.",
    ["domladder", "slippageradar", "execintel"],
    ["monitor_liquidity", "execute_with_context"],
    ["Ctrl+2", "/liq {coin}"],
    ["Pre-trade liquidity check", "Identify resting liquidity walls", "Spread regime monitoring"],
    ["spread bps", "book imbalance", "mid price", "level size"],
  ),
  entry(
    "chart",
    "Chart",
    "OHLCV",
    "Price action surface with operational HUD — regime ribbon, stress gauge, stream pulse, and spread context.",
    "Structure and context must be visible without leaving the execution surface.",
    "Professionals anchor timeframe to holding period: scalp on 1m–5m, swing on 15m–1h, macro overlay on 4h+.",
    "Regime shift from range to trend often precedes volatility expansion; stress elevation warns of thin liquidity.",
    ["surveillance", "execintel", "memorydesk"],
    ["read_volatility", "execute_with_context"],
    ["Ctrl+1", "/chart {coin}"],
    ["Structure identification", "Event marker review", "Replay scenario study"],
    ["regime", "stress index", "spread", "OHLCV"],
  ),
  entry(
    "intelligence",
    "Tactical Wire",
    "TAPE",
    "Ranked tactical intelligence vectors — whale prints, funding flips, liquidation proximity, agentic fusion signals.",
    "Tape is the fastest institutional signal surface for abnormal flow on the active symbol.",
    "Professionals treat critical vectors as interrupt signals; watch-level as background context until confirmed by book.",
    "Whale buy into thin ask stack = absorption test; cluster of large sells in 60s = cascade risk.",
    ["alerts", "intelengine", "newswire"],
    ["read_order_flow", "alert_response"],
    ["/intel"],
    ["Whale flow monitoring", "Funding flip detection", "Cascade early warning"],
    ["notional USD", "severity", "confidence", "acceleration"],
  ),
  entry(
    "ticket",
    "Trade Ticket",
    "EXEC",
    "Hyperliquid-native order entry — side, size, price type, agent-approved submission path.",
    "Execution is the only panel that changes risk. Everything else is context.",
    "Professionals size from slippage radar output, never from chart alone. Confirm reduce-only when de-risking.",
    "Market orders in elevated stress = tail slippage risk; limits at depth walls improve average fill.",
    ["slippageradar", "positions", "hyperbook"],
    ["execute_with_context", "monitor_liquidity"],
    ["Ctrl+E", "/exec buy {coin} {size}"],
    ["Scaled entry", "Reduce-only exit", "Limit at liquidity wall"],
    ["estimated slippage", "spread", "order notional"],
  ),
  entry(
    "positions",
    "Positions",
    "RISK",
    "Authoritative open risk from clearinghouse — size, entry, unrealized PnL, margin context.",
    "Position truth must match exchange state. Ticket intent ≠ filled risk.",
    "Professionals reconcile after every fill; watch PnL flash only as secondary confirmation.",
    "Rising unrealized loss + widening spread = reduce priority; flat book + profit = trail or scale logic.",
    ["portfoliodesk", "ticket", "surveillance"],
    ["execute_with_context"],
    [],
    ["Post-fill verification", "Risk cap monitoring", "Session PnL review"],
    ["unrealized PnL", "notional exposure", "margin usage"],
  ),
  entry(
    "domladder",
    "DOM Ladder",
    "DOM OFA",
    "Depth-of-market ladder showing microstructure and order-flow-aligned price levels.",
    "Tick-level execution requires ladder view, not aggregate book alone.",
    "Professionals use DOM when scaling in/out at specific levels or detecting spoof-like flicker.",
    "Repeated pull of large bid levels = false support; sustained ask reload = distribution.",
    ["hyperbook", "execintel", "slippageradar"],
    ["monitor_liquidity", "read_order_flow"],
    ["/depth {coin}"],
    ["Level-based scaling", "Microstructure surveillance", "Sweep detection"],
    ["level imbalance", "aggressor side", "reload frequency"],
  ),
  entry(
    "slippageradar",
    "Slippage Radar",
    "SLIP RADAR",
    "Pre-trade execution quality estimator — spread, impact, and liquidity vacuum warnings.",
    "Institutional desks reject blind market orders. Slippage radar is the gate.",
    "Professionals check radar before every market submit; widen threshold in stress regimes.",
    "Impact score spike = use limits or reduce size; stable spread = market acceptable for urgency.",
    ["ticket", "hyperbook", "execintel"],
    ["execute_with_context", "monitor_liquidity"],
    ["/monitor funding"],
    ["Pre-submit check", "Size adjustment", "Venue quality comparison"],
    ["estimated slippage bps", "spread", "impact score"],
  ),
  entry(
    "alerts",
    "Alert Engine",
    "RULE ENGINE",
    "Rule-based tape evaluator — OI surge, funding flip, whale prints (≥$75k), liquidation clusters.",
    "Humans cannot watch every metric. Rules surface exceptions worth attention.",
    "Professionals click alert → chart focus → confirm with book before acting.",
    "Three large sells in 60s = liquidation cascade setup; funding flip negative = carry regime change.",
    ["intelligence", "surveillance", "mobiledesk"],
    ["alert_response"],
    ["/alerts {coin}"],
    ["Exception monitoring", "Whale print response", "Cascade preparation"],
    ["OI change %", "funding rate", "cluster notional", "whale notional"],
  ),
  entry(
    "surveillance",
    "Surveillance",
    "SURVEILLANCE",
    "Regime inference, market stress gauge, and atmosphere monitoring for the active symbol.",
    "Regime tells you which playbook applies — mean reversion vs momentum vs stand aside.",
    "Professionals glance surveillance before increasing size; critical stress = reduce default size.",
    "Stress + bearish regime = defensive posture; low stress + trend = continuation framework.",
    ["chart", "systemicintel", "derivdesk"],
    ["read_volatility"],
    ["Ctrl+M"],
    ["Regime classification", "Stress-based sizing", "Session risk posture"],
    ["stress index", "regime label", "book imbalance"],
  ),
];

const ADVANCED: ComponentGuideEntry[] = [
  entry(
    "macro",
    "Macro Matrix",
    "MACRO",
    "Cross-asset macro tickers — rates, indices, FX — for session context.",
    "Crypto does not trade in isolation. Macro session sets risk appetite.",
    "Professionals note DXY and yields before crypto open; high-impact calendar = reduce leverage.",
    "Rising yields + strong DXY often pressure risk assets; equity strength can lift beta alts.",
    ["globaldesk", "systemicintel", "chart"],
    ["read_volatility"],
    ["/macro"],
    ["Pre-market context", "FOMC/CPI session prep"],
    ["DXY", "US10Y", "index futures"],
  ),
  entry(
    "execintel",
    "Execution Intelligence",
    "EXEC INTEL",
    "Order flow analytics, liquidity heatmap, execution quality, microstructure pressure.",
    "Post-trade and pre-trade analytics close the execution feedback loop.",
    "Professionals review aggression and sweep metrics after large fills to grade desk quality.",
    "Aggressor buy imbalance + rising CVD = initiative; iceberg suspicion = hidden size.",
    ["domladder", "slippageradar", "liveexec"],
    ["read_order_flow", "monitor_liquidity"],
    [],
    ["Fill quality review", "Liquidity map", "Sweep detection"],
    ["aggression score", "efficiency", "imbalance"],
  ),
  entry(
    "derivdesk",
    "Derivatives Desk",
    "DERIVATIVES DESK",
    "Funding, open interest, volatility surfaces for perp-focused workflows.",
    "Derivatives positioning drives carry and squeeze dynamics.",
    "Professionals monitor funding extremes for crowded trade unwind risk.",
    "Extreme positive funding + rising OI = long crowding; negative funding squeeze = short pain.",
    ["surveillance", "portfoliodesk", "systemicintel"],
    ["interpret_funding", "read_volatility"],
    [],
    ["Funding arb context", "OI regime shifts", "Vol surface read"],
    ["funding rate", "OI change", "realized vol"],
  ),
  entry(
    "portfoliodesk",
    "Portfolio Desk",
    "PORTFOLIO DESK",
    "Multi-asset exposure, treasury view, and portfolio-level risk.",
    "Single-coin focus misses correlation and net beta.",
    "Professionals use portfolio desk for net exposure caps across correlated alts.",
    "Concentrated beta + systemic stress = hedge or reduce gross.",
    ["positions", "systemicintel", "billingdesk"],
    ["execute_with_context"],
    [],
    ["Net exposure review", "Treasury allocation", "Correlation check"],
    ["gross exposure", "beta", "VaR proxy"],
  ),
  entry(
    "newswire",
    "Market Newswire",
    "NEWSWIRE",
    "Operational newswire — ranked tape, incidents, briefings, personalized delivery.",
    "Information distribution is infrastructure, not a Twitter feed.",
    "Professionals enable desktop delivery for critical incidents only; avoid alert fatigue.",
    "Exchange outage incident = halt size; depeg incident = stablecoin basis review.",
    ["intelligence", "dailyops", "mobiledesk"],
    ["alert_response"],
    ["Ctrl+N", "/newswire"],
    ["Incident response", "Briefing consumption", "Webhook syndication"],
    ["incident severity", "priority score"],
  ),
  entry(
    "memorydesk",
    "Market Memory",
    "MARKET MEMORY",
    "Historical archive, regime analogs, and chart replay for context.",
    "Markets rhyme. Memory desk anchors current conditions to prior regimes.",
    "Professionals run replay on analog scenarios before sizing into unfamiliar volatility.",
    "Current vol + funding profile matching prior cascade analog = defensive default.",
    ["chart", "researchdesk", "explaindesk"],
    ["read_volatility"],
    [],
    ["Regime analog search", "Historical replay", "Archive research"],
    ["analog score", "regime label", "replay progress"],
  ),
  entry(
    "explaindesk",
    "Operator Guide",
    "GUIDE",
    "Institutional operational education — glossary, scenarios, workflows, replay training.",
    "Dense terminals require embedded mentorship, not external PDFs alone.",
    "Professionals use explain mode during onboarding and when exploring new desks.",
    "Scenario replay teaches structure; workflows teach repeatable desk habits.",
    ["memorydesk", "commercial", "operatordesk"],
    ["monitor_liquidity", "read_order_flow", "interpret_funding", "read_volatility"],
    ["?", "/guide", "/explain"],
    ["Panel glossary", "Scenario library", "Guided workflows"],
    ["guide score", "replay progress"],
  ),
  entry(
    "operatorjournal",
    "Operator Journal",
    "JOURNAL",
    "Persistent session tracking, decision journal, execution-quality grading, behavioral detection and end-of-session review.",
    "Traders improve through review and reflection — not just more screen time.",
    "Professionals log thesis + emotion + confidence on every decision, then debrief at session end.",
    "Behavioral flags surface revenge-trading and overtrading before they compound losses.",
    ["execintel", "slippageradar", "traderjournal"],
    ["read_order_flow", "monitor_liquidity"],
    ["/journal", "/review"],
    ["Log a decision", "Run end-of-session review", "Review behavioral flags"],
    ["operator grade", "execution score", "discipline score"],
  ),
  entry(
    "livementor",
    "Live Mentor",
    "LIVE MENTOR",
    "A calm operational mentor that translates live market events into plain English — what happened, why it matters, what to check next, and what mistake to avoid.",
    "Markets move faster than beginners can interpret; the mentor narrates structure as it changes.",
    "Professionals glance here to confirm an event's meaning, then act from their own read — never blindly.",
    "Pin important moments to market memory so the same lesson compounds over time.",
    ["alerts", "intelligence", "hyperbook"],
    ["alert_response", "monitor_liquidity"],
    [],
    ["Read a live event", "Pin a market lesson", "Toggle beginner / pro depth"],
    ["events explained", "lessons saved"],
  ),
  entry(
    "liveexec",
    "Live Execution",
    "LIVE EXEC",
    "Multi-asset live execution desk with presets for scalping, MM, treasury workflows.",
    "Professional execution is a workspace, not a single ticket.",
    "Professionals apply desk presets to align panel emphasis with strategy.",
    "Scalping preset elevates DOM + slippage; treasury preset elevates portfolio + risk.",
    ["ticket", "execintel", "slippageradar"],
    ["execute_with_context"],
    [],
    ["Desk preset selection", "Multi-asset monitoring"],
    ["latency", "fill rate", "exec score"],
  ),
  entry(
    "marketcmd",
    "Market Command",
    "MARKET CMD",
    "Situational command vitals — systemic intel, coverage, distribution, execution analytics composite.",
    "Command layer synthesizes subsystems into one operational picture.",
    "Professionals use during fast markets for single-glance situational awareness.",
    "Low situational score = widen margins and reduce size until clarity returns.",
    ["systemicintel", "marketcoverage", "unifiedops"],
    ["alert_response"],
    [],
    ["Session situational read", "Ops handoff"],
    ["situational score"],
  ),
  entry(
    "operatordesk",
    "Operator AI",
    "OPERATOR AI",
    "Workflow-oriented AI desk — factual context, not trade signals.",
    "AI reduces cognitive load when bounded to organization and explanation.",
    "Professionals query for structure ('summarize funding on ETH') not directives ('should I buy').",
    "Use after alerts to compress context, not before independent analysis.",
    ["copilot", "intelengine", "explaindesk"],
    [],
    [],
    ["Context compression", "Workflow Q&A"],
    ["assistant score"],
  ),
];

/** Generic fallback for panels without bespoke copy yet. */
function genericEntry(id: string, title: string, telemetry: string): ComponentGuideEntry {
  return entry(
    id,
    title,
    telemetry,
    `Operational console for ${title.toLowerCase()} — composes Equilibrium subsystem engines into a unified desk surface.`,
    "Institutional workflows require subsystem visibility without leaving the terminal.",
    "Professionals open this desk when the workflow phase demands that domain — not as a default home screen.",
    "Interpret outputs relative to active asset, regime, and session liquidity.",
    ["explaindesk", "unifiedops"],
    [],
    [`/focus ${id}`],
    ["Subsystem monitoring", "Cross-desk drill-down"],
    ["subsystem score", "vitals"],
  );
}

const GENERIC_IDS: [string, string, string][] = [
  ["copilot", "AI Copilot", "AI LAYER"],
  ["proactive", "Proactive Monitor", "AGENTIC"],
  ["teamdesk", "Team Net", "TEAM NET"],
  ["diagnostics", "Diagnostics", "TOTE"],
  ["alphalab", "Alpha Lab", "QUANT"],
  ["infra", "Platform Infra", "PLATFORM"],
  ["decision", "Market Context", "CONTEXT"],
  ["knowledgegraph", "Knowledge Graph", "KNOWLEDGE GRAPH"],
  ["traderjournal", "Trader Journal", "JOURNAL"],
  ["research", "Research", "RESEARCH"],
  ["dailyops", "Daily Operations", "DAILY OPS"],
  ["marketcoverage", "Market Coverage", "COVERAGE"],
  ["reliability", "Reliability", "RELIABILITY"],
  ["ingestion", "Data Ingest", "INGEST"],
  ["intelengine", "Market Intelligence", "INTEL"],
  ["collab", "Collaboration", "COLLAB"],
  ["enterpriseops", "Enterprise Ops", "ENTERPRISE"],
  ["integrations", "Integrations", "INTEGRATE"],
  ["propintel", "Proprietary Intel", "EQ INTEL"],
  ["ecosystem", "Crypto Financial OS", "ECOSYSTEM"],
  ["globalstrategy", "Global Strategy", "GLOBAL STRAT"],
  ["commercial", "Product · Commercial", "PRODUCT"],
  ["systemicintel", "Systemic Intel", "SYSTEMIC INTEL"],
  ["researchdesk", "Research Desk", "RESEARCH DESK"],
  ["platformdesk", "Platform Desk", "PLATFORM DESK"],
  ["mobiledesk", "Mobile Ops", "MOBILE OPS"],
  ["opscommand", "Ops Command", "OPS COMMAND"],
  ["billingdesk", "Billing Desk", "BILLING DESK"],
  ["deskops", "Desk Ops", "DESK OPS"],
  ["globaldesk", "Global Intel", "GLOBAL INTEL"],
  ["unifiedops", "Unified Ops", "UNIFIED OPS"],
  ["maturitydesk", "Terminal Polish", "TERMINAL POLISH"],
  ["livedeploy", "Live Deploy", "LIVE DEPLOY"],
];

export class ComponentRegistryEngine {
  private static cache: ComponentGuideEntry[] | null = null;

  static all(): ComponentGuideEntry[] {
    if (!ComponentRegistryEngine.cache) {
      ComponentRegistryEngine.cache = [
        ...CORE,
        ...ADVANCED,
        ...GENERIC_IDS.map(([id, title, tel]) => genericEntry(id, title, tel)),
      ];
    }
    return ComponentRegistryEngine.cache;
  }

  static get(id: string): ComponentGuideEntry | null {
    return ComponentRegistryEngine.all().find((e) => e.id === id) ?? null;
  }

  /** Always returns a guide entry — creates on-the-fly copy for unknown panel ids. */
  static resolve(id: string, title?: string, telemetry?: string): ComponentGuideEntry {
    const existing = ComponentRegistryEngine.get(id);
    if (existing) return existing;
    const label =
      title ??
      id
        .replace(/([a-z])([A-Z])/g, "$1 $2")
        .replace(/desk$/i, " Desk")
        .replace(/-/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
    return genericEntry(id, label, telemetry ?? "SYS");
  }

  static search(query: string): ComponentGuideEntry[] {
    const q = query.trim().toLowerCase();
    if (!q) return ComponentRegistryEngine.all();
    return ComponentRegistryEngine.all().filter(
      (e) =>
        e.id.includes(q) ||
        e.title.toLowerCase().includes(q) ||
        e.telemetry.toLowerCase().includes(q) ||
        e.operationalExplanation.toLowerCase().includes(q),
    );
  }
}
